# Generated by Django 5.1.4 on 2026-09-14 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CierreMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
            ],
            options={
                'verbose_name': 'cierre mensual',
                'verbose_name_plural': 'cierres mensuales',
                'db_table': 'cierre_mensual',
                'ordering': ['-periodo__anio', '-periodo__mes'],
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('cierre_mensual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diarios', to='contabilidad_finanzas.cierremensual')),
            ],
            options={
                'verbose_name': 'diario',
                'verbose_name_plural': 'diarios',
                'db_table': 'diario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FacturaCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_venta_id', models.PositiveIntegerField(blank=True, null=True)),
                ('orden_compra_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('COMPRA', 'Compra')], max_length=20)),
                ('numero', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='contabilidad_finanzas.diario')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'db_table': 'factura_cabecera',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad_finanzas.facturacabecera')),
            ],
            options={
                'verbose_name': 'detalle de factura',
                'verbose_name_plural': 'detalles de factura',
                'db_table': 'factura_detalle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='año')),
                ('mes', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'período',
                'verbose_name_plural': 'períodos',
                'db_table': 'periodo',
                'ordering': ['-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('anio', 'mes'), name='uq_periodo_anio_mes')],
            },
        ),
        migrations.AddField(
            model_name='cierremensual',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_mensuales', to='contabilidad_finanzas.periodo'),
        ),
        migrations.AddConstraint(
            model_name='facturacabecera',
            constraint=models.UniqueConstraint(fields=('tipo', 'numero'), name='uq_factura_tipo_numero'),
        ),
    ]
