# Generated by Django 5.1.4 on 2026-09-04 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrdenCompra',
            fields=[
                ('estadoordencompra_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de orden de compra',
                'verbose_name_plural': 'Estados de orden de compra',
                'db_table': 'estado_orden_compra',
                'ordering': ['estadoordencompra_id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('ordencompra_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='compra_y_proveedores.estadoordencompra')),
                ('proveedor', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='compra_y_proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'db_table': 'orden_compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('ordencompradetalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_id', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(db_column='preciounitario', decimal_places=2, max_digits=12)),
                ('orden_compra', models.ForeignKey(db_column='ordencompra_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compra_y_proveedores.ordencompra')),
            ],
            options={
                'verbose_name': 'Detalle de orden de compra',
                'verbose_name_plural': 'Detalles de orden de compra',
                'db_table': 'orden_compra_detalle',
            },
        ),
    ]
