# Generated by Django 5.1.4 on 2026-09-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='producto_id',
            field=models.PositiveIntegerField(default=1, help_text='1 a 1 con Producto.', unique=True),
            preserve_default=False,
        ),
    ]
