# Generated by Django 5.1.4 on 2026-09-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra_y_proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compra_y_proveedores.ordencompra')),
            ],
            options={
                'verbose_name': 'Detalle de orden de compra',
                'verbose_name_plural': 'Detalles de orden de compra',
                'db_table': 'orden_compra_detalle',
            },
        ),
    ]
