# Generated by Django 5.1.4 on 2026-09-29 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scm", "0001_modelos_iniciales"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(db_column="id", primary_key=True, serialize=False)),
                ("nombre", models.CharField(db_column="nombre", max_length=150)),
                (
                    "telefono",
                    models.CharField(blank=True, db_column="telefono", max_length=50, null=True),
                ),
                (
                    "email",
                    models.CharField(blank=True, db_column="email", max_length=100, null=True),
                ),
                (
                    "direccion",
                    models.CharField(blank=True, db_column="direccion", max_length=200, null=True),
                ),
                (
                    "cuil",
                    models.CharField(
                        blank=True,
                        db_column="cuil",
                        help_text="Para buscar al cliente por CUIL en Registrar venta.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "condicion_iva",
                    models.CharField(
                        blank=True,
                        db_column="condicion_iva",
                        help_text="Usado para sugerir el tipo de comprobante (A/B/C) automáticamente.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("AC", "Activo"), ("OF", "Baja")],
                        db_column="estado",
                        default="AC",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "cliente",
                "ordering": ["id_cliente"],
            },
        ),
        migrations.CreateModel(
            name="EstadoOrdenVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Estado de orden de venta",
                "verbose_name_plural": "Estados de orden de venta",
                "db_table": "estado_orden_venta",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="NotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("saldo_a_favor", models.BooleanField(default=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Nota de crédito",
                "verbose_name_plural": "Notas de crédito",
                "db_table": "nota_credito",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetalleNotaCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cantidad_devuelta", models.PositiveIntegerField()),
                (
                    "destino",
                    models.CharField(
                        choices=[
                            ("STOCK_DISPONIBLE", "Stock disponible"),
                            ("PRODUCTO_DANADO", "Producto dañado"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_nota_credito",
                        to="scm.producto",
                    ),
                ),
                (
                    "nota_credito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="ventas.notacredito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de nota de crédito",
                "verbose_name_plural": "Detalles de nota de crédito",
                "db_table": "detalle_nota_credito",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OrdenVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "forma_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("DEBITO", "Débito"),
                            ("CREDITO", "Crédito"),
                            ("TRANSFERENCIA", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "numero_comprobante",
                    models.CharField(
                        blank=True,
                        help_text='Ej: "B-0002145". Se muestra en el historial de Devoluciones.',
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FACTURA_A", "Factura A"),
                            ("FACTURA_B", "Factura B"),
                            ("FACTURA_C", "Factura C"),
                            ("NOTA_VENTA", "Nota de venta"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_venta",
                        to="ventas.cliente",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_venta",
                        to="ventas.estadoordenventa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_venta_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de venta",
                "verbose_name_plural": "Ordenes de venta",
                "db_table": "orden_venta",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddField(
            model_name="notacredito",
            name="orden_venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notas_credito",
                to="ventas.ordenventa",
            ),
        ),
        migrations.CreateModel(
            name="Anulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("motivo", models.CharField(max_length=100)),
                ("detalle", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "orden_venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anulacion",
                        to="ventas.ordenventa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anulación",
                "verbose_name_plural": "Anulaciones",
                "db_table": "anulacion",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="OrdenVentaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("precio_unitario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descuento", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "orden_venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="ventas.ordenventa",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_orden_venta",
                        to="scm.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de orden de venta",
                "verbose_name_plural": "Detalles de orden de venta",
                "db_table": "orden_venta_detalle",
                "ordering": ["id"],
            },
        ),
    ]
