# Generated by Django 5.1.4 on 2026-09-25 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='condicion_iva',
            field=models.CharField(blank=True, db_column='condicion_iva', help_text='Usado para sugerir el tipo de comprobante (A/B/C) automáticamente.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuil',
            field=models.CharField(blank=True, db_column='cuil', help_text='Para buscar al cliente por CUIL en Registrar venta.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='numero_comprobante',
            field=models.CharField(blank=True, help_text='Ej: "B-0002145". Se muestra en el historial de Devoluciones.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='tipo_comprobante',
            field=models.CharField(blank=True, choices=[('FACTURA_A', 'Factura A'), ('FACTURA_B', 'Factura B'), ('FACTURA_C', 'Factura C'), ('NOTA_VENTA', 'Nota de venta')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordenventadetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia')], max_length=20),
        ),
        migrations.CreateModel(
            name='Anulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden_venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anulacion', to='ventas.ordenventa')),
            ],
            options={
                'verbose_name': 'Anulación',
                'verbose_name_plural': 'Anulaciones',
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_a_favor', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='ventas.ordenventa')),
            ],
            options={
                'verbose_name': 'Nota de crédito',
                'verbose_name_plural': 'Notas de crédito',
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField()),
                ('destino', models.CharField(choices=[('STOCK_DISPONIBLE', 'Stock disponible'), ('PRODUCTO_DANADO', 'Producto dañado')], max_length=30)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_nota_credito', to='ventas.producto')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.notacredito')),
            ],
            options={
                'verbose_name': 'Detalle de nota de crédito',
                'verbose_name_plural': 'Detalles de nota de crédito',
            },
        ),
    ]
